version: '3.5'

# This compose file configures a setup with nginx and the interleave-it API server running
# together, to mimic a setup one uses in production for this service.

services:
  interleave-it:
    image: jerrington/interleave-it
    restart: unless-stopped
    stop_grace_period: 5s
    ## comment out to enable running in 'prod' mode
    entrypoint: /app/debug
    ports:
      - "5000:5000" # HTTP port (host:container)
    environment:
      - BIND=0.0.0.0:5000
      - OUTPUT_DIR=/output
      - UPLOAD_DIR=/uploads
      - WORKERS=4
      - OUTPUT_BASE_URL=http://localhost:8080/output/
    volumes:
      - output:/output
      - uploads:/uploads
      # for development of the API server, we bind mount the whole source code into the container:
      - type: bind
        source: .
        target: /app

  proxy:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - type: bind
        source: ./html
        target: /usr/share/nginx/html
        read_only: true
      - type: bind
        source: default.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
      - output:/output

volumes:
  output:
  uploads:
